### ISSUE TITLE
Acala bridge + swap :   1010 invalid transaction, transaction has bad signature

### ISSUE THREAD

**Issue by remi-parain** [Zondax/ledger-acala#19]
I have a ledger live dot account and i'm using polkadot.js  browser extension to use Defi.

I was able to load my  polkadot account into polkadot.js ( and ledger polkadot ledger app, deveopped by your company).

[on Acala Bridge](https://apps.acala.network/bridge),  i bridged my Dot from Polkadot to Acala network  .

I signed from my polkadot ledger app, then my balance  is recognized by Acala network.
then [on Acala swap](https://apps.acala.network/swap) , i can't swap my Dot to any other currency 
 ( it fails each time i sign the transaction with my acala ledger app) .
 
 i'm starting to really worry as i can't use the bridge in the other way (Acala to Polkadot ) to get my dots back,  for the exact same reason : 
 
 **1010 invalid transaction, transaction has bad signature**
 
 i found  this ticket 
 https://github.com/polkadot-js/apps/issues/4487
 but it only covers KSM and DOT, and the  "hidden" menu contained  in ledger app only work for Polkadot (ksm app) or Kusama (Polkadot app) ( is there  any hidden menu in acala app?) 
 I really hope there is a solution for this as it seems your app is the root cause of the issue
 

:link: [zboto Link](https://app.clickup.com/t/39j88af)

**Comment by carlosala** [comment]
Try to follow the steps from [here](https://zondax.ch/blog/crowdloans)

**Comment by carlosala** [comment]
Feel free to reopen if this doesn't solve your problem!

**Comment by remi-parain** [comment]
Thank you very much @carlosala  ! 
first, i thought you were missing with me ! 
i read carefully the link you gave me and i was able to unblock  my  situation !!!
i can't thank you more than those few words ( if our path cross IRL one day, i'll owe you some drinks :) ) .
for anyone reading this  thread, in the same situation, try this :
- open Acala App  in ledger 
- set Expert mode to "Enabled"
- "set Account as "Legacy"
Review and validate all the warnings ( it seems to switch to "crowdloans" mode).
try your swap again.
in my case, it worked !!
hopefully , in a year i'll be able to bridge back to dot  :sweat_smile:

**Comment by Ciudadan0X** [comment]
Hello good,

20-25 days ago, I decided to transfer my Dots to Acala to swap Lcdot.

Download the Acala App and connect my ledger, allowing me to change them to Acala through the bridge but when I want to do the swap it gives me an error:

dex: swapWithExactSupply
1010: Invalid Transaction: Transaction has a bad signature.

I’m desperate because my ledger sees the address and recognizes it but it won’t let me sign the transaction and now it won’t let me move or do anything with my dots, which I understand I’ve lost.
But I don’t know why because I did everything with my ledger.

26W5dnzNkVFdniPfg7RzesAuDe3sUhMYYdoqcdiaA7g25see

-This is the address, but it gives me a signature error and I don’t know how to correct it, directly in the brigde I was awarded this… and I don’t know what to do?

Where can I ask for help with this error?.....................


### After reading this comment, I managed to swap from Dot to Lcdot (following these instructions). My question is when the Lcdots are released, there will be no problems transferring the Dots of the future? in my situation?


Thank you very much for the help and comments.

**Comment by LuckymanTeam** [comment]
I have encountered significant issues while trying to manage my ACA tokens, and I've attached screenshots to illustrate the problems. Despite following the steps on the Acala app platform, I'm facing a 'bad signature' error when attempting to claim vested ACA tokens, making it impossible to proceed with the transaction. Furthermore, the Acala app is not recognizing my Ledger wallet as a compatible account type for transactions, as it is identified with the Polkadot (DOT) chain and not Acala.

This has placed me in a difficult situation where I'm unable to claim or transfer any of my ACA tokens, even though they are visible in my portfolio. The error messages suggest a signature issue and an account type incompatibility, but I'm unsure how to resolve these. I have provided the screenshots for a clearer understanding of the problems at hand.

Could you please help me understand how to correct these issues? Is there a way to reconfigure my Ledger to work with the Acala app, or is there another method to claim and transfer my tokens? Your expertise and guidance in this matter would be invaluable.

Looking forward to your prompt response.

**Comment by LuckymanTeam** [comment]
![444](https://github.com/Zondax/ledger-acala/assets/80419402/c0fc79c8-36f1-4900-af7a-70b0049ffee9)
![333](https://github.com/Zondax/ledger-acala/assets/80419402/b6d57356-eff6-4c75-989f-79c86265bc87)
![22](https://github.com/Zondax/ledger-acala/assets/80419402/0ef59b0a-9e1e-45d4-999a-adf21f863c3a)
![111](https://github.com/Zondax/ledger-acala/assets/80419402/d556b1f6-0233-4470-a1d4-39a65632ce02)

**Comment by ftheirs** [comment]
Hi @LuckymanTeam, have you checked the previous replies? Are you sure that you're using the right account in polkadot js and did you try with Legacy and Crowdloan modes on the app?
https://github.com/Zondax/ledger-acala/issues/19#issuecomment-1345654782

**Comment by LuckymanTeam** [comment]
Of course, here's the complete message for you to copy and paste:

Hello @ftheirs,

Despite following your advice and recommendations, I regret to inform you that I have not been successful in resolving the issue with managing my Acala tokens through my Ledger wallet. I've checked the previous replies, used both Legacy and Crowdloan modes in the app, updated all necessary software, and even tried to adjust the Ledger settings, but all my attempts have ended in failure.

With each attempt, I encounter new difficulties, and at this point, I feel stuck without a clear path to a solution. The 'bad signature' error persists, and my account is still not recognized as a compatible account type in the Acala app, despite my efforts.

I truly need your help to navigate this situation. Is there any step or setting that I might have missed? Your expertise and knowledge would be incredibly valuable in finding a solution to my problem.

Additionally, I'm considering sending screenshots and detailing the steps I've undertaken to further clarify my predicament. Would that be helpful for diagnosing the issue? Honestly, I've been grappling with this for over two years now, and it's incredibly frustrating not being able to make any progress with these tokens. Any insight or guidance you could provide would be immensely appreciated, as I'm at my wits' end trying to find a resolution.

Thank you once again for your patience and willingness to assist. Your support means a lot to me.

Best regards,
@LuckymanTeam
