### ISSUE TITLE
Acala network stake $ACA not support

### ISSUE THREAD

**Issue by okmind** [Zondax/ledger-acala#29]
Acala network stake $ACA not support，https://github.com/AcalaNetwork/Acala/issues/2668#issue-2035739696

:link: [zboto Link](https://app.clickup.com/t/8693ak5jx)

**Comment by ftheirs** [comment]
Hi @okmind, here you have a list of all pallets and calls supported by the Acala Ledger app. Can you tell me which is the one that is not supported?
Check also that if you are using NanoS, you'll need to install the XL version.

https://github.com/Zondax/ledger-acala/blob/main/README.md

**Comment by okmind** [comment]
OK. There is my ledger information and acala version

Ledger: Nano X
Acala version: 3.2180.2

**Comment by carlosala** [comment]
As Bryan stated https://github.com/AcalaNetwork/Acala/issues/2668#issuecomment-1850985170 staking is not supported in Ledger Acala app. According to [acala docs](https://guide.acalaapps.wiki/staking/aca-staking-via-ledger), you have an option with proxy.
